# Generated by Django 5.2.6 on 2025-11-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='clarity',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='engagement',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recommend',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='relevance',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='usefulness',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10),
        ),
    ]
