# Generated by Django 5.2.6 on 2025-11-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='certification',
            field=models.FileField(null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='certification_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('In Review', 'In Review'), ('Approved', 'Approved'), ('Hold', 'Hold'), ('Rejected', 'Rejected')], default='in review', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Art', 'Art'), ('Cooking', 'Cooking'), ('Music', 'Music'), ('Other', 'Other')], max_length=50),
        ),
    ]
