# Generated by Django 5.2.6 on 2025-11-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_mentor',
        ),
    ]
